name: Run Warrior gRPC

on:
  workflow_dispatch:

jobs:
  run-grpc:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository 
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install grpcurl
      - name: Install grpcurl
        run: |
          sudo apt update
          sudo apt install -y curl unzip
          GRPCURL_VERSION="1.16.0"
          curl -L -o grpcurl.zip https://github.com/fullstorydev/grpcurl/releases/download/v${GRPCURL_VERSION}/grpcurl_${GRPCURL_VERSION}_linux_x86_64.zip
          unzip grpcurl.zip
          sudo mv grpcurl /usr/local/bin/

      # Step 3: Call gRPC methods and save responses
      - name: Call getBarbarian
        run: grpcurl -proto warrior.proto -d '{}' grpc-hillel-warriors.hillel.it:50051 warrior.WarriorServer/getBarbarian > warrior_barbarian.json

      - name: Call getAssassin
        run: grpcurl -proto warrior.proto -d '{}' grpc-hillel-warriors.hillel.it:50051 warrior.WarriorServer/getAssassin > warrior_assassin.json

      - name: Call getEnchantress
        run: grpcurl -proto warrior.proto -d '{}' grpc-hillel-warriors.hillel.it:50051 warrior.WarriorServer/getEnchantress > warrior_enchantress.json

      - name: Call getWerewolf
        run: grpcurl -proto warrior.proto -d '{}' grpc-hillel-warriors.hillel.it:50051 warrior.WarriorServer/getWerewolf > warrior_werewolf.json

      - name: Call getWarriorByName
        run: grpcurl -proto warrior.proto -d '{"name":"Barbarian"}' grpc-hillel-warriors.hillel.it:50051 warrior.WarriorServer/getWarriorByName > warrior_by_name.json

      - name: Call getAllWarriors
        run: grpcurl -proto warrior.proto -d '{}' grpc-hillel-warriors.hillel.it:50051 warrior.WarriorServer/getAllWarriors > all_warriors.json

      # Step 4: Upload all responses as artifacts
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: warrior-responses
          path: |
            warrior_barbarian.json
            warrior_assassin.json
            warrior_enchantress.json
            warrior_werewolf.json
            warrior_by_name.json
            all_warriors.json
