name: Run Warrior gRPC

on:
  workflow_dispatch:

jobs:
  run-grpc:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install grpcurl
      - name: Install grpcurl
        run: |
          sudo apt update
          sudo apt install -y curl wget tar
          GRPCURL_VERSION="1.9.3"
          URL="https://github.com/fullstorydev/grpcurl/releases/download/v${GRPCURL_VERSION}/grpcurl_${GRPCURL_VERSION}_linux_x86_64.tar.gz"
          echo "Downloading grpcurl version ${GRPCURL_VERSION}..."
          wget -O grpcurl.tar.gz "$URL"
          tar -xvzf grpcurl.tar.gz
          sudo mv grpcurl /usr/local/bin/
          sudo chmod +x /usr/local/bin/grpcurl
          grpcurl -version

      # Step 3: Call Warrior gRPC methods and save responses
      - name: Call all Warrior methods
        run: |
          mkdir -p warrior_responses
          for method in getBarbarian getAssassin getEnchantress getWerewolf
          do
            grpcurl -proto warrior.proto -d '{}' grpc-hillel-warriors.hillel.it:50051 warrior.WarriorServer/$method > warrior_responses/$method.json
          done

      # Step 4: Upload artifacts with results
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: warrior-responses
          path: warrior_responses/
